# Generated by Django 4.0.4 on 2024-01-17 19:13

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_cobro', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cobrar')),
                ('importe_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Recibido')),
                ('qna_cobro', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Qna. cobro')),
                ('anio_cobro', models.DecimalField(decimal_places=0, default=2024, max_digits=4, verbose_name='Año cobro')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha cobro')),
                ('estatus', models.BooleanField(blank=True, choices=[(0, 'Pendiente'), (1, 'Recibido')], default=False, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'db_table': 'Cobro',
                'ordering': ['anio_cobro', 'qna_cobro', 'id'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Pagar a:')),
                ('corte', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Corte')),
                ('tipo_pago', models.CharField(choices=[('Q', 'Quincena'), ('M', 'Mensual'), ('B', 'Bimestral'), ('S', 'Semestral')], default='Q', max_length=1, verbose_name='Tipo pago')),
                ('mes_empieza', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Mes empieza')),
                ('anio_empieza', models.DecimalField(decimal_places=0, default=2024, max_digits=4, verbose_name='Año empieza')),
                ('mes_termina', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Mes termina')),
                ('anio_termina', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Año termina')),
                ('estatus', models.BooleanField(blank=True, choices=[(0, 'Baja'), (1, 'Activo')], default=False, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Deudor',
                'verbose_name_plural': 'Deudores',
                'db_table': 'Deudor',
                'ordering': ['nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Sobrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_sobrante', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sobrante')),
                ('qna_sobrante', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Qna. sobrante')),
                ('anio_sobrante', models.DecimalField(decimal_places=0, default=2024, max_digits=4, verbose_name='Año sobrante')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Sobrante',
                'verbose_name_plural': 'Sobrantes',
                'db_table': 'Sobrante',
                'ordering': ['anio_sobrante', 'qna_sobrante'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pagar')),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pagado')),
                ('qna_pagar', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Qna. pagar')),
                ('anio_pagar', models.DecimalField(decimal_places=0, default=2024, max_digits=4, verbose_name='Año pagar')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('fecha_pagado', models.DateField(blank=True, null=True, verbose_name='Fecha pagado')),
                ('estatus', models.BooleanField(blank=True, choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Cancelado')], default=False, null=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_deudor', to='core.deudor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['deudor', 'anio_pagar', 'qna_pagar'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
