# Generated by Django 4.0.4 on 2024-01-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cobro_estatus_alter_deudor_estatus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deudor',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='sobrante',
            unique_together={('anio_sobrante', 'qna_sobrante')},
        ),
    ]
