# Generated by Django 4.0.4 on 2024-01-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deudor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudor',
            name='mes_empieza',
        ),
        migrations.RemoveField(
            model_name='deudor',
            name='mes_termina',
        ),
        migrations.AddField(
            model_name='deudor',
            name='qna_empieza',
            field=models.IntegerField(choices=[('1', '1a. qna.'), ('2', '2a. qna.'), ('3', '3a. qna.'), ('4', '4a. qna.'), ('5', '5a. qna.'), ('6', '6a. qna.'), ('7', '7a. qna.'), ('8', '8a. qna.'), ('9', '9a. qna.'), ('10', '10a. qna.'), ('11', '11a. qna.'), ('12', '12a. qna.'), ('13', '13a. qna.'), ('14', '14a. qna.'), ('15', '15a. qna.'), ('16', '16a. qna.'), ('17', '17a. qna.'), ('18', '18a. qna.'), ('19', '19a. qna.'), ('20', '20a. qna.'), ('21', '21a. qna.'), ('22', '22a. qna.'), ('23', '23a. qna.'), ('24', '24a. qna.')], default=1, verbose_name='Qna empieza'),
        ),
        migrations.AddField(
            model_name='deudor',
            name='qna_termina',
            field=models.IntegerField(choices=[('1', '1a. qna.'), ('2', '2a. qna.'), ('3', '3a. qna.'), ('4', '4a. qna.'), ('5', '5a. qna.'), ('6', '6a. qna.'), ('7', '7a. qna.'), ('8', '8a. qna.'), ('9', '9a. qna.'), ('10', '10a. qna.'), ('11', '11a. qna.'), ('12', '12a. qna.'), ('13', '13a. qna.'), ('14', '14a. qna.'), ('15', '15a. qna.'), ('16', '16a. qna.'), ('17', '17a. qna.'), ('18', '18a. qna.'), ('19', '19a. qna.'), ('20', '20a. qna.'), ('21', '21a. qna.'), ('22', '22a. qna.'), ('23', '23a. qna.'), ('24', '24a. qna.')], default=0, verbose_name='Qna termina'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='anio_cobro',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024, verbose_name='Año cobro'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='qna_cobro',
            field=models.IntegerField(choices=[('1', '1a. qna.'), ('2', '2a. qna.'), ('3', '3a. qna.'), ('4', '4a. qna.'), ('5', '5a. qna.'), ('6', '6a. qna.'), ('7', '7a. qna.'), ('8', '8a. qna.'), ('9', '9a. qna.'), ('10', '10a. qna.'), ('11', '11a. qna.'), ('12', '12a. qna.'), ('13', '13a. qna.'), ('14', '14a. qna.'), ('15', '15a. qna.'), ('16', '16a. qna.'), ('17', '17a. qna.'), ('18', '18a. qna.'), ('19', '19a. qna.'), ('20', '20a. qna.'), ('21', '21a. qna.'), ('22', '22a. qna.'), ('23', '23a. qna.'), ('24', '24a. qna.')], default=1, verbose_name='Qna. cobro'),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='anio_empieza',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024, verbose_name='Año empieza'),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='anio_termina',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=0, verbose_name='Año termina'),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='anio_pagar',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024, verbose_name='Año pagar'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='qna_pagar',
            field=models.IntegerField(choices=[('1', '1a. qna.'), ('2', '2a. qna.'), ('3', '3a. qna.'), ('4', '4a. qna.'), ('5', '5a. qna.'), ('6', '6a. qna.'), ('7', '7a. qna.'), ('8', '8a. qna.'), ('9', '9a. qna.'), ('10', '10a. qna.'), ('11', '11a. qna.'), ('12', '12a. qna.'), ('13', '13a. qna.'), ('14', '14a. qna.'), ('15', '15a. qna.'), ('16', '16a. qna.'), ('17', '17a. qna.'), ('18', '18a. qna.'), ('19', '19a. qna.'), ('20', '20a. qna.'), ('21', '21a. qna.'), ('22', '22a. qna.'), ('23', '23a. qna.'), ('24', '24a. qna.')], default=1, verbose_name='Qna. pagar'),
        ),
        migrations.AlterField(
            model_name='sobrante',
            name='anio_sobrante',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2024, verbose_name='Año sobrante'),
        ),
        migrations.AlterField(
            model_name='sobrante',
            name='qna_sobrante',
            field=models.IntegerField(choices=[('1', '1a. qna.'), ('2', '2a. qna.'), ('3', '3a. qna.'), ('4', '4a. qna.'), ('5', '5a. qna.'), ('6', '6a. qna.'), ('7', '7a. qna.'), ('8', '8a. qna.'), ('9', '9a. qna.'), ('10', '10a. qna.'), ('11', '11a. qna.'), ('12', '12a. qna.'), ('13', '13a. qna.'), ('14', '14a. qna.'), ('15', '15a. qna.'), ('16', '16a. qna.'), ('17', '17a. qna.'), ('18', '18a. qna.'), ('19', '19a. qna.'), ('20', '20a. qna.'), ('21', '21a. qna.'), ('22', '22a. qna.'), ('23', '23a. qna.'), ('24', '24a. qna.')], default=1, verbose_name='Qna. sobrante'),
        ),
    ]
